version: '2.0'

services: 
    ganache:
        build: docker/ganache

    waves:
        image: wavesplatform/waves-private-node
        
    golang:
        image: golang
        links: 
            - ganache
            - waves
        volumes: 
            - ./:/go/src/rh_tests:rw
        command: sh -c "cd /go/src/rh_tests/ether; go run rh_tests && go test && cd /go/src/rh_tests/waves && go test"

