version: '2.0'

services: 
    ganache:
        build: docker/ganache

    waves:
        image: wavesplatform/waves-private-node

    abigen:
        build: docker/abigen
        volumes: 
            - ./ether:/source:rw
                    
    golang:
        image: golang
        links: 
            - ganache
            - waves
        volumes: 
            - ./:/go/src/rh_tests:rw
        command: sh -c "cd /go/src/rh_tests; ./test.sh"

